"""Add image URL to posts

Revision ID: 56f00c7b95ea
Revises: 001_add_post_indexes
Create Date: 2026-09-17 11:39:16.065366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f00c7b95ea'
down_revision = '001_add_post_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('additional_stories', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('additional_stories_post_id_fkey'),
            type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'posts',
            ['post_id'],
            ['id'],
            referent_schema='public'
        )

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('comments_post_id_fkey'),
            type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None,
            'posts',
            ['post_id'],
            ['id'],
            referent_schema='public'
        )

    # image_url may already exist in the production database because
    # it was previously added manually.
    op.execute("""
        ALTER TABLE public.posts
        ADD COLUMN IF NOT EXISTS image_url VARCHAR(500)
    """)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column(
            'views',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text('0')
        )
        batch_op.alter_column(
            'likes',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text('0')
        )
        batch_op.alter_column(
            'dislikes',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text('0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column(
            'dislikes',
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text('0')
        )
        batch_op.alter_column(
            'likes',
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text('0')
        )
        batch_op.alter_column(
            'views',
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text('0')
        )
        batch_op.drop_column('image_url')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered. Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('comments_post_id_fkey'),
            'posts',
            ['post_id'],
            ['id']
        )

    with op.batch_alter_table('additional_stories', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered. Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('additional_stories_post_id_fkey'),
            'posts',
            ['post_id'],
            ['id']
        )

    # ### end Alembic commands ###